// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/OrangePortraitEventPoster-1q3_Nw/DeepOrangePoster.tsx": () => import("../components/mockups/templates/OrangePortraitEventPoster-1q3_Nw/DeepOrangePoster.tsx")
};
